# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

linters:
  enable:
    - gofmt
    - gocyclo
    - golint
    - misspell
    - typecheck
    - errcheck
    - dogsled
    - unconvert
    - nakedret
    - scopelint
issues:
  exclude-use-default: false
  exclude:
    - Error return value of `.*Close` is not checked
    - Error return value of `.*Flush` is not checked
    - Error return value of `.*Write` is not checked
    - Error return value of `.*Fprintf` is not checked
    - Error return value of `os.Remove` is not checked
    - Error return value of `os.RemoveAll` is not checked
